name: AnimatedMenu
version: 3.2.8
main: me.megamichiel.animatedmenu.AnimatedMenuPlugin
author: megamichiel
softdepend: [Vault, PlayerPoints, PlaceholderAPI, AnimationLib]
api-version: 1.15

commands:
  animatedmenu:
    description: Plugin command
    usage: /<command>
